
version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php81fpm
    container_name: php81-app
    restart: unless-stopped
    ports:
    - 8000:80
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app
networks:
  app:
    driver: bridge
